name: Build Yuzu Custom Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Checkout a la version antigua
        shell: powershell
        run: |
          git checkout 8c4aca60a9bc0286af415b458e35162f52538d16
          git submodule update --init --recursive

      - name: Configurar CMake
        shell: powershell
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DYUZU_USE_BUNDLED_VULKAN=ON

      - name: Compilar
        shell: powershell
        run: |
          cmake --build build --config Release

      - name: Guardar ejecutable
        uses: actions/upload-artifact@v4
        with:
          name: Yuzu-Custom-Windows
          path: build/bin/Release/
